---
- name: ensure the .ssh directory exists.
  file:
    path: "{{ ansible_user_dirÂ }}/.ssh"
    state: directory

- name: Copy SSH keys
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

